version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.sqlite
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=your-secret-key-change-in-production
    volumes:
      # Mount the data directory to persist SQLite database
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s